Optimization and Bug fix - Use StringBuilder instead of String - Fix #6321, Fix #9007: The BROWSE action is not supported on the current platform! - Fix #7696: EmptyStackException on JTextPane.setText() - Fix #2205: ExceptionInInitializerError on DragSource.getDragThreshold() - Fix #14417: NullPointerException on MediatorModel.model().getStrategy().instance() - Fix #21394: NullPointerException on stop() - Fix #6456: IllegalArgumentException on getHeaderFieldKey() - Fix #26274: IllegalComponentStateException on show() - Fix #22668: Assistive Technology not found - Fix #23877: NoClassDefFoundError on java/nio/file/Paths - Fix #7497, Fix #8247, Fix #8332: BufImgSurfaceData cannot be cast to XRSurfaceData on drawImage() - Fix #4658, Fix #2224: Fix #1797 Multiple Exceptions on model.addRow() - Fix #3127, Fix #6772: Multiple Exceptions on paintAll() - Fix #6350: ArrayIndexOutOfBoundsException on paint() - Fix #4770: ArrayIndexOutOfBoundsException on chunkTab.append() - Fix #4012: ArrayIndexOutOfBoundsException on paint() - Fix #4657, #1860: Multiple Exceptions on setRowCount() - Fix #863: Exception on insertString() - Sonar code quality